---

name: molecule-setup-ci
    
on:
  push: 
    branches: ["main"]
    paths-ignore:
        - 'README.md'
        - '**/*.md'
        - .gitignore
        - ./meta/main.yml

permissions:
  contents: read

env:
  ROLE_NAME: "sample"

jobs:
  molecule-setup-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install ubuntu dependencies
        run: |
          sudo apt-get install python3.10-venv

      - name: Create and activate python-venv
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv ~/.venv/ansible_env
          source ~/.venv/ansible_env/bin/activate
          python3 -m pip install -r requirements.txt

      - name: Install Virtualbox 7.1.4
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
          sudo apt-get update
          wget https://download.virtualbox.org/virtualbox/7.1.4/virtualbox-7.1_7.1.4-165100~Ubuntu~$(lsb_release -cs)_amd64.deb
          sudo apt-get install -y linux-headers-$(uname -r) dkms
          sudo apt-get install ./virtualbox-7.1_7.1.4-165100~Ubuntu~$(lsb_release -cs)_amd64.deb
    
      - name: Verify VirtualBox installation
        run: VBoxManage --version

      - name: Install vagrant
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install vagrant -y

      - name: Verify Vagrant installation
        run: vagrant --version

      - name: Setup role and molecule scenario
        run: |
          ansible-galaxy role init ${{ env.ROLE_NAME }}
          cd ${{ env.ROLE_NAME }}
          molecule init scenario

...